name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:            # 👈 Add this block
      contents: write       # required for pushing tags & changelog commits
      issues: write         # optional: allow release notes on issues
      pull-requests: write  # optional: allow release notes on PRs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0    # 👈 Ensure full git history (tags included)

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
